### ISSUE TITLE
Set cookie expire in minutes?

### ISSUE THREAD

**Issue by jithinjose2** [carhartl/jquery-cookie#211]
There is only an option to expire cookies in days? Can you please add an option to create cookies which expire in minutes?

**Comment by Messilimeng** [comment]
Can you give me a example to  create cookies in minutes?

**Comment by carhartl** [comment]
@Messilimeng http://stackoverflow.com/questions/1197928/how-to-add-30-minutes-to-a-javascript-date-object

**Comment by FagnerMartinsBrack** [comment]
@Messilimeng js-cookie also has a Wiki that answers your question: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#expire-cookies-in-less-than-a-day

**Comment by carhartl** [comment]
:thumbsup:
