### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by kalenjordan** [carhartl/jquery-cookie#220]
Sorry if this is a really dumb question, but any interest in adding composer support and submitting to packagist?  

It seems like there are some different positions out there in regard to the best way to version javascript within a PHP project:
https://github.com/composer/composer/issues/524#issuecomment-4912681
http://stackoverflow.com/a/14417969/1117286

I did see that jquery itself is already on packagist:
https://packagist.org/packages/components/jquery

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/172#issuecomment-209286184 for detailed explanations of how to make js-cookie working with composer.
