### ISSUE TITLE
Solution for Sauce Labs/Travis failing on PRs

### ISSUE THREAD

**Issue by carhartl** [carhartl/jquery-cookie#268]
So far only workarounds exist, though a solution is being worked on, see

http://support.saucelabs.com/entries/25614798-How-can-we-set-up-an-open-source-account-that-runs-tests-on-people-s-pull-requests-

**Comment by FagnerMartinsBrack** [comment]
@carhartl 

[Savage](https://github.com/twbs/savage) seems to be provide a solution for this. Last commit was 5 days ago so it seems to be actively maintained.

Worth take a look.

**Comment by cvrebert** [comment]
Very actively maintained, and used by Bootstrap! I would be happy to answer any questions if you need help setting up an instance :-)

**Comment by FagnerMartinsBrack** [comment]
@cvrebert do you know any open-source infra-structure that can be used with Savage? Or we should setup our own server?

**Comment by cvrebert** [comment]
@FagnerMartinsBrack Not offhand. It's just a simple HTTP server JAR that runs on an arbitrary TCP port.
If you already have a server, it should be possible to run Savage alongside other apps.
I happen to run Bootstrap's instance on the smallest DigitalOcean droplet size.

**Comment by carhartl** [comment]
So it needs to be something Java capable? I can set something up on Heroku.

**Comment by FagnerMartinsBrack** [comment]
Moved to js-cookie/js-cookie#13
