### ISSUE TITLE
Default Path

### ISSUE THREAD

**Issue by jlukic** [carhartl/jquery-cookie#284]
Default options for $.cookie have path as undefined. This causes cookies without the option `path: '/'` to be set to the URL of the current page.

There are very few instances where a developer would want to set a cookie 'per page'. I nominate adding the default path option to be `path: '/'`

**Comment by FagnerMartinsBrack** [comment]
> This has been discussed before (in the issues).

X-ref: https://github.com/carhartl/jquery-cookie/issues/2
