### ISSUE TITLE
Return $.cookie so AMD/CJS user can use it directly

### ISSUE THREAD

**Issue by JSteunou** [carhartl/jquery-cookie#319]
By returning $.cookie you will allow AMD/CJS user to just

```
var $cookie = require('jquery.cookie');
```

instead of 

```
var $ = require('jquery');
require('jquery.cookie');
```

which could be avoid because `jquery.cookie` has jquery as dependency.

**Comment by carhartl** [comment]
I've merged #339, which is supposed to fix this.
