### ISSUE TITLE
bower.json excludes itself

### ISSUE THREAD

**Issue by matthewp** [carhartl/jquery-cookie#329]
You're ignores includes `*.json` which means `bower.json` itself is not included. This is useful for tooling purposes.  Consider changing? https://github.com/carhartl/jquery-cookie/blob/master/bower.json#L13

**Comment by carhartl** [comment]
It seems this is (now?) obsolete. 

The bower.json spec states:

> Note: symbolic links will always be ignored. However bower.json will never be ignored.

https://github.com/bower/bower.json-spec
