### ISSUE TITLE
expires option-Test fails after changing to expire fraction-commit in 1.4.1

### ISSUE THREAD

**Issue by psychotammi** [carhartl/jquery-cookie#331]
Hi,

I've cloned the repository and started the test-server after the grunt-test failed 'cause I wanted to see what's the problem and to check whether the script works in old legacy browser 'cause I didn't find a answer on that in the readme.
I am here in Germany on GMT+0200 (until next Sunday, then it will be GMT+0100) and the 'expires option as days from now'-test went wrong with a difference of 1 hour in the 2 strings.
The result by `$.cookie('c', 'v', { expires: 7 })` seems to have the wrong time after changing the writing of the cookie from `t.setDate(t.getDate() + days)` to `t.setTime(+t + days * 864e+5)` and casting t from Date to Number and the number misses it's timecode-dependency so it is always UTC in v1.4.1

I hope you understand what I want to say, I will add some screenshots to help understanding.

Thx,
Michael

![jquery-cookie_expires-option_1 4 0](https://cloud.githubusercontent.com/assets/6105378/4702947/d148f8c0-5866-11e4-92f9-020af780304b.png)

![jquery-cookie_expires-option_1 4 1](https://cloud.githubusercontent.com/assets/6105378/4702951/d8a0c134-5866-11e4-984e-e8bb687c8d32.png)

**Comment by carhartl** [comment]
If I understand that right, the problem will occur when we set expires using a value so that there will be a daylight savings change inbetween then and the time of expiration.

**Comment by carhartl** [comment]
...yes, it's that. Interesting, trying to fix it.
