### ISSUE TITLE
Cookies got expired on page reload/refresh

### ISSUE THREAD

**Issue by rohan-chd** [carhartl/jquery-cookie#345]
Hello Klaus,

I am using this Cookie plugin but i am facing some problems there. Actually i am using this plugin in a chat app. But sometimes it work and sometime not. Here is some issues:
1) I set a cookie in first function and when i try to get the same cookie in another function with in same file it gave me nothing. But sometimes it start working and gave me right value there.
2)  I am trying to update the cookie but it also not working and after updating then existing cookie i print that cookie again but still it gave me the old values.
3) On page refresh/reload the cookies got expired itself and give me again the default values. I also set the expiry date to 7 days but still not working.

Can you please help me in this matter? I will be really thankful to you for this great help. If you want to check the code, let me know. I will provide you the code access as well.

Regards,
Rohan.

**Comment by sudheer594** [comment]
Please provide the sample code to reproduce the issue,it would be hard to understand without test case.

**Comment by carhartl** [comment]
Possible things to look out for: race condition regarding 1) writing and reading of the cookie from different functions. Impossible to tell here. Regarding 2): quite possibly a problem with `path` not defined, see the Readme. Could also apply to 1). 3) I don't have an idea at all. 

Just some quick ideas... I can't really help with it, it would at least require a simplified test case, I won't be able to digg into the entire application code.

Also: Make sure to use the latest version.

**Comment by rohan-chd** [comment]
Hey sudheer594. I can provide you the code but the thing is to setup test case is not that much easy as i am trying to apply this on a major project and its not possible to replicate the things anywhere else. But i will try to setup it on some test server if possible.

Thanks Klaus, I will try the solutions you gave me.

**Comment by rohan-chd** [comment]
@carhartl i used the solution you gave me. I mean i am using it with path its working fine now. But now when i try to remove its not working. Like i set the cookie as:
$.cookie('cookieLimitName','10', { path: '/' }); and when i try to delete it by this $.removeCookie('cookieLimitName', { path: '/' }); its not working. 

Can you suggest me here as well?

Regards,
Rohan

**Comment by rohan-chd** [comment]
@carhartl no worries. $.removeCookie thing is fixed. I was setting the same query in another function without 'path'. As soon as i set the path, the $.removeCookie starts working.
