### ISSUE TITLE
Multiple cookies not working on Internet Explorer (IE)

### ISSUE THREAD

**Issue by rohan-chd** [carhartl/jquery-cookie#346]
Hello @carhartl  i am facing another strange issue in IE. This thing is working fine for other browser but in IE its not working. Please have a look below here for a sample case. I am not asking you to debug my code but just asking for what are the possibilities where i am wrong? 

Suppose i have 3 functions.
**************
function function_1(){
      //Some dynamic cookies through loop
     for (var i = 0; i < 100; i++) {
	$.cookie("dynamicName","dynamicValue", { path: '/' });
     } 
} 
function function_2(){
      //Call to 3'rd function
      function_3();
}
function function_3(){
     //Set 2 new cookies
     $.cookie('abc','0', { path: '/' });
     $.cookie('xyz','1', { path: '/' });
}

**************
You can see in these 3 functions, i set dynamic cookies in first function. In second function i just called another 3'rd function 'function_3()'. And in function 'function_3()', i am creating 2 new cookies again. 

Now the issue is: If i try to create 2 new cookies in function_3() like i did here, It destroy the site session but if i create only one cookie in function_3() its works fine and sites work perfectly without any session failure.

This problem is only occurring in IE but for other browsers its work fine without any issue. Can you suggest me what could be the reasons behind all this?

--
Regards,
Rohan.

**Comment by carhartl** [comment]
I have absolutely no clue. I think you may have more luck asking these kind of questions on Stackoverflow...

Which version of IE are you referring to?

**Comment by rohan-chd** [comment]
I am working with IE9.
