### ISSUE TITLE
 SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by HuangShaoTian** [carhartl/jquery-cookie#347]
hi, when I import the script in the head (after the jquery.js script), it get an error on console, says: " SyntaxError: expected expression, got '<'"
![error](https://cloud.githubusercontent.com/assets/4961965/6056432/dcaa78ee-ad4b-11e4-8d2e-d953e2d6a31e.jpg)

**Comment by carhartl** [comment]
My assumption here is that you're referencing the script incorrectly and the web server is serving a 404 html page. Make sure the js file is where you're referencing it from. 

This has nothing to do with the functionality of the plugin though.

**Comment by xiaomao155** [comment]
hello,I have encountered this problem , I ask you how to solve

**Comment by xiaomao155** [comment]
I have encountered this problem , I ask you how to solve

**Comment by karlosjota** [comment]
My solution with React
<script> change for <script type="text/jsx">

**Comment by tahiryasin** [comment]
If you are on Linux, check CHMOD of your JS file
