### ISSUE TITLE
bower jquery.cookie.min.js not exist

### ISSUE THREAD

**Issue by sargin48** [carhartl/jquery-cookie#350]
bower jquery.cookie.min.js not exist.
would you insert this file ?

thanks.

**Comment by carhartl** [comment]
Please see https://github.com/carhartl/jquery-cookie/releases

**Comment by sargin48** [comment]
you are right but 
when user install this plugin with 
cmd -> bower install jquery.cookie --save
there aren't any jquery.cookie.min.js   minified file.
i meant this.

**Comment by FagnerMartinsBrack** [comment]
It is a good practice to use a build process to concatenate and minify vendor files downloaded using bower. There is a common situation where you need the unminified files for debugging and minified files for deploying to production.
