### ISSUE TITLE
Expires in minutes?

### ISSUE THREAD

**Issue by elalemanyo** [carhartl/jquery-cookie#352]
Hi,
How is the best way to set a expire time in minutes?

Thanks

**Comment by carhartl** [comment]
You can either pass an instance of Date to expires (thus creating one and setting it to some minutes from "now") or pass a fraction of a day, e.g. 5 minutes:  `expires: 1 / (24 * 60) * 5`.

**Comment by elalemanyo** [comment]
ok, thanks!
