### ISSUE TITLE
potentially override global options in each call

### ISSUE THREAD

**Issue by macgyver** [carhartl/jquery-cookie#353]
more of a comment - have you ever thought about adding an additional parameter to override the global options on a per-call basis? I was just discovering that it gets a bit messy to switch between JSON-encoded and non-encoded cookies - maybe it just belies a messy cookie strategy but it's not always in my control.

**Comment by carhartl** [comment]
Yes, it gets messy and turns out that json config flag was not the best idea. We plan to completely retire this in version 2 and handle json automatically.
