### ISSUE TITLE
document.cookie value is undefined

### ISSUE THREAD

**Issue by cloudEgy** [carhartl/jquery-cookie#355]
Hello,
I'm trying to get value of cookie in javascript run at ruby on rails, but when I'm trying to print its value .... I got empty string or 'undefined' although I'm sure that the value of the cookie is setted
Thank you so much.

**Comment by carhartl** [comment]
What is the name of the cookie you're trying to read? Maybe rails is obfuscating the cookie in some way, or you simply don't have access to it, due to path or httpOnly attributes...?
