### ISSUE TITLE
bower install jquery.cookie fails!

### ISSUE THREAD

**Issue by samirprakash** [carhartl/jquery-cookie#357]
Hi,

We have a dependency of jquery.cookie in our project and we have been using this for a long time without any issues.

Today, bower install jquery.cookie has started failing with below error:

i>bower install jquery.cookie --save
bower jquery.cookie#*           cached git://github.com/carhartl/jquery-cookie.git#1.4.1
bower jquery.cookie#*         validate 1.4.1 against git://github.com/carhartl/jquery-cookie.git#*
bower jquery.cookie#*          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/carhartl/jquery-co

Additional error details:
fatal: unable to access 'https://github.com/carhartl/jquery-cookie.git/': Failed connect to github.com:443; No error

**Comment by macgyver** [comment]
did you add a new Firewall to your network recently? This doesn't like an
issue that's remotely related to the jquery.cookie project.

**Comment by samirprakash** [comment]
I am checking with the network team as well as that was my first thought. But the crazy thing is that I tried it from out side the firewall as well and:

1. bower install jquery.cookie sometimes works
2. bower install jquery,cookie --save fails

**Comment by carhartl** [comment]
GitHub seems to be troubled once again by a DDoS attack, that's why the repo is not available (and occasionally is).

https://status.github.com/
