### ISSUE TITLE
json option prevents parsing regular cookies

### ISSUE THREAD

**Issue by d07RiV** [carhartl/jquery-cookie#358]
If I use the json option, the plugin fails to parse regular string cookies set from HTTP headers.

**Comment by FagnerMartinsBrack** [comment]
@d07RiV  Do you have an example?

**Comment by d07RiV** [comment]
Just set $.cookie.json to true and it won't be able to parse regular strings if they aren't quoted.

E.g.
PHP:

    setcookie("test", "value");

JS:

    $.cookie.json = true;
    $.cookie("test") // returns undefined

The source reads:

		try {
			// Replace server-side written pluses with spaces.
			// If we can't decode the cookie, ignore it, it's unusable.
			// If we can't parse the cookie, ignore it, it's unusable.
			s = decodeURIComponent(s.replace(pluses, ' '));
			return config.json ? JSON.parse(s) : s;
		} catch(e) {}

**Comment by carhartl** [comment]
If you set json to true, we expect them to be json parseable... at the moment. In version 2.0 this is going to be handled more gracefully and automatically.

**Comment by carhartl** [comment]
See #285
