### ISSUE TITLE
Cookie with Safari 8.0.6 (Yosemite)

### ISSUE THREAD

**Issue by powermike** [carhartl/jquery-cookie#363]
Hi,

On Safari 8.0.6 (last Yosemite version) I have:
```
$.cookie('presentation')
```
that returns
```
""
```
Then I do:
```
$.cookie('presentation', 'read', {expires: 1, path: '/'})
```
It returns
```
"presentation=read; expires=Thu, 28 May 2015 13:11:29 GMT; path=/"
```
Right after I call:
```
$.cookie('presentation')
```
it strangely returns this
```
""
```

but if I do:
```
$.cookie('presentation', 'read')
```
It returns:
```
"presentation=read"
```
Then I do:
```
$.cookie('presentation')
```
it returns the proper value:
```
"read"
```

As a comparison, on chrome I have the proper behavior.

I hope it can help.

Regards.

**Comment by FagnerMartinsBrack** [comment]
Hi, new issues should be opened at https://github.com/js-cookie/js-cookie/issues.
Check out the latest release and confirm if the issue is fixed: https://github.com/js-cookie/js-cookie/releases

**Comment by carhartl** [comment]
Fwiw, the second time you execute `$.cookie('presentation', 'read')` a session cookie is being written and that worked, that's why then reading will return "read".

But why wouldn't one with expires be written...?

**Comment by FagnerMartinsBrack** [comment]
@powermike In js-cookie v2 the default path was set to the whole site (`/`) and is tested against Safari 8.

Can you please confirm if any of the followings are true or false:
1. It fails in previous versions of safari?
2. It fails in js-cookie [2.0.0-beta.1](https://github.com/js-cookie/js-cookie/tree/v2.0.0-beta.1)?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
