### ISSUE TITLE
'expires: 0' deletes cookie

### ISSUE THREAD

**Issue by sp00n** [carhartl/jquery-cookie#364]
This may be intended or not, but to me it wasn't what I expected. Setting the expiry value to 0 immediately deletes the cookie. I was hoping it would transform the cookie into a session cookie instead (I've included the cookie functions within a wrapper).

Luckily there's a quick fix for this: extend the check on line 88 as following: `if (typeof options.expires === 'number' && options.expires != 0) {`

Of course you could also just pass a value that's not actually considered a number, but passing a 0 seemed more descriptive to me. And I don't think it's cluttering the code too much.

**Comment by FagnerMartinsBrack** [comment]
Hi, new issues should be opened at https://github.com/js-cookie/js-cookie/issues as from https://github.com/carhartl/jquery-cookie/commit/d72bb07e29962330db61aae1eda07f6312419840.
Check out the latest release and confirm if the issue is fixed: https://github.com/js-cookie/js-cookie/releases

**Comment by FagnerMartinsBrack** [comment]
Moved to https://github.com/js-cookie/js-cookie/issues/45
