### ISSUE TITLE
when server end set new cookie value, $.cookie still return the old value.

### ISSUE THREAD

**Issue by superwf** [carhartl/jquery-cookie#366]
Is jquery-cookie cache it?
When I refresh the page, $.cookie can return the new cookie value.

**Comment by FagnerMartinsBrack** [comment]
Hi, new issues should be opened at https://github.com/js-cookie/js-cookie/issues as from d72bb07.
Check out the latest release and confirm if the issue is fixed: https://github.com/js-cookie/js-cookie/releases
