### ISSUE TITLE
Can't remove cookie if parent path has the same name

### ISSUE THREAD

**Issue by quangld** [carhartl/jquery-cookie#367]
$.cookie('CookieTest','local')
"CookieTest=local"
$.cookie('CookieTest','root',{path:'/'})
"CookieTest=root; path=/"
$.removeCookie('CookieTest')
false

If you accidentally have 2 cookies with the same name, you can't remove the local cookie without removing the same cookie name saved in the parent path.
So in this above example, you have to:
$.removeCookie('CookieTest',{path:'/'})
true

then
$.removeCookie('CookieTest',{path:'/'})
true

**Comment by FagnerMartinsBrack** [comment]
Hi, this project is frozen, new issues should be opened at https://github.com/js-cookie/js-cookie/issues as stated in the [README](https://github.com/carhartl/jquery-cookie/tree/d72bb07e29962330db61aae1eda07f6312419840#important).

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/52#issuecomment-113960440
