### ISSUE TITLE
wrong month set by date

### ISSUE THREAD

**Issue by joubertredrat** [carhartl/jquery-cookie#368]
Hi guys,

I'm testing this plugin using expires by date, but month isn't working fine. When I set a month, my cookie receive more 1 month than I put on date.

Example:
$.cookie("name", "Test", {expires: new Date(2015, 10, 25, 17, 01, 00)});

When I see cookie data, expires is 11/25/2015 17:01:00

If I set month 06, on cookie is 07, and just like in all my tests.

I don't know if this is a issue, but I hope to be helped. Thanks

**Comment by FagnerMartinsBrack** [comment]
Hi, new issues should be opened at https://github.com/js-cookie/js-cookie/issues.

**Comment by FagnerMartinsBrack** [comment]
The problem is that `new Date()` interprets the month as [zero-index based numbering](https://en.wikipedia.org/wiki/Zero-based_numbering).

``` shell
$ new Date(2015, 10, 25, 17, 01, 00)
Wed Nov 25 2015 17:01:00 GMT-0200 (Horário brasileiro de verão)

$ new Date(2015, 0, 25, 17, 01, 00)
Sun Jan 25 2015 17:01:00 GMT-0200 (Horário brasileiro de verão)
```

**Comment by joubertredrat** [comment]
Hi @FagnerMartinsBrack 

This is strange, my date function works normally.

```
> var d = new Date(2015, 06, 24, 11, 00, 00);
undefined
> d.getMonth();
6
> d.getUTCMonth();
6
> $.cookie("name", "Me", {expires: d});
"name=Me; expires=Fri, 24 Jul 2015 14:00:00 GMT"
```

Note: time difference is normal, here is UTC -3:00, but month is strange.

# 

Edit 

Really @FagnerMartinsBrack, have a bug on Date();

```
> d.getMonth();
6
> d.toDateString();
"Fri Jul 24 2015"
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

Thanks for the help.
