### ISSUE TITLE
Remove cookie does not work

### ISSUE THREAD

**Issue by hackash** [carhartl/jquery-cookie#369]
Remove function does not work on chrome. I tried both of provided examples but still doesn't work.

**Comment by FagnerMartinsBrack** [comment]
Hi, new issues should be opened at https://github.com/js-cookie/js-cookie/issues.
Check out the latest release and confirm if the issue is fixed: https://github.com/js-cookie/js-cookie/releases

Note: Make sure you pass the same path, secure and domain options when deleting a cookie.
