### ISSUE TITLE
Cant delete/remove cookies

### ISSUE THREAD

**Issue by Jyotie** [carhartl/jquery-cookie#376]
here is my page where I am not able to remove cookie.
I have set it like this using this plugin
$.cookie('Authorization', response.Authorization);

where response is from API 

I am trying to remove is like this,

$.removeCookie('Authorization');

but it always returns false.

please help....

**Comment by FagnerMartinsBrack** [comment]
Hi, this repository is not being actively maintained and was superseded by https://github.com/js-cookie/js-cookie, new issues should be opened there. If you want to use with jquery, check the [latest version from 1.x.x release (1.5.1)](https://github.com/js-cookie/js-cookie/tree/v1.5.1).

Also, the returning value from `$.removeCookie` was removed in js-cookie version 2, I wouldn't rely on that.

**Comment by FagnerMartinsBrack** [comment]
Btw, I recommend posting questions about usage in StackOverflow first. There is a higher probability to get a satisfactory answer there since it has more Google visibility.

**Comment by carhartl** [comment]
@Jyotie Given the little amount of information you're providing it's hardly possible for us to provide any help...

**Comment by Jyotie** [comment]
Hello Sir,
This is solved. I was setting cookie under one folder path and was trying to remove it from root path. This I come to know after reading one article where I come to know that we have to mention the path while setting and removing the cookie. 
Thanks for this wonderful plugin :)
