### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by mborah** [carhartl/jquery-cookie#378]
My code in HTML page

<a href="abcd.html" class="link">My Link</a>

<script>
$(document).ready(function () {
  $(".link").on("click", function () {          
    $.cookie('myCookie', 'In this string I want to break the Line like \n second line starts', { expires: 2  , path: '/' });    
  });
});
</script>

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/carhartl/jquery-cookie/issues/379#issuecomment-159687492
