### ISSUE TITLE
[NuGet] Align naming convention between minified and base .js files in package

### ISSUE THREAD

**Issue by b-c-lucas** [carhartl/jquery-cookie#381]
When I went to update my solution's jquery.cookie NuGet package from 1.4.0 to 1.4.1, I loved seeing the addition of a minified JS file; however, there's some file naming weirdness - the minified JS file has a version in the file name while the unminified version does not. The mismatch makes it impossible to choose between the two files when leveraging MVC's bundling powers. Any chance the NuGet package can either add a version to the base .file or remove the version from the minified file?

Love the plugin, and would love to migrate up to js-cookie if/when I get npm hooked into my solution.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/carhartl/jquery-cookie/issues/152#issuecomment-12953584

**Comment by carhartl** [comment]
I still have no clue when it comes to NuGet :)
