### ISSUE TITLE
$.removeCookie is not deleting cookie in Chrome

### ISSUE THREAD

**Issue by suvonkar** [carhartl/jquery-cookie#382]
$.removeCookie is not deleting cookie in Chrome.

Please refer the below attachment of screenshot. The screenshot is taken from the Chrome settings -> All Cookie and site data.

![cookie in chrome settings](https://cloud.githubusercontent.com/assets/12408613/11975415/96f09aa0-a993-11e5-8886-3686b4a3f10b.jpg)

The above screenshot is clearly showing that one cookie(name : !Proxy!proxyJSESSIONID, and path : /stockquote/rest/auth) is available. But when
 `$.removeCookie('!Proxy!proxyJSESSIONID', { path: '/stockquote/rest/auth'});` 
code is executed it is returning **false** and not **deleting the cookie**.

![removecookie is not working](https://cloud.githubusercontent.com/assets/12408613/11975504/b6084cfc-a994-11e5-8df1-ca6a30a1b606.jpg)

I am using **jQuery Cookie Plugin v1.4.1**.

**Comment by carhartl** [comment]
From where are you trying to remove the cookie? You have to be within the same path (or "below") in order to delete such a cookie.

**Comment by carhartl** [comment]
When you're unsuccessfully trying to delete the cookie, which path are you in?

**Comment by suvonkar** [comment]
I am trying to delete cookie from one of JS file available under **/stockquote/**. Also the cookie path is **/stockquote/rest/auth**

Please note it is working fine in FF. The issue with Chrome only.

**Comment by suvonkar** [comment]
@carhartl , Finally I have found an alternative.

`$.cookie('!Proxy!proxyJSESSIONID', '', { expires: -1, path: '/stockquote/rest/auth'});`
1. Setting the value as blank('') and
2. Set one additional option `expires : -1`

But $.removeCookie is not working.

**Comment by carhartl** [comment]
That's a bit odd because nothing else is what `$.remiveCookie` does: https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js#L110

**Comment by carhartl** [comment]
I don't see any good reason why calling it directly would work in Chrome, though a call wrapped in a function would not...

**Comment by suvonkar** [comment]
@carhartl , I have figured out the issue.

I have downloaded the plugin from the link http://github.com/carhartl/jquery-cookie/zipball/v1.4.1 , what I have got from jquery plugin page(https://plugins.jquery.com/cookie/). It seems like this version of code available in this zip is not the version you are referring.

The code available in the jquery plugin page.

``` javascrip
    $.removeCookie = function (key, options) {
        if ($.cookie(key) === undefined) {
            return false;
        }
        // Must not alter options, thus extending a fresh object...
        $.cookie(key, '', $.extend({}, options, { expires: -1 }));
        return !$.cookie(key);
    };
```

**Comment by carhartl** [comment]
Ah, I see. I remember there was a fix for a similar problem here: 4527b3725ce7b61066e6aa12bbe8d20c0371a1d7 but we moved to https://github.com/js-cookie/js-cookie before releasing it. 

You want to download and use https://github.com/js-cookie/js-cookie/releases/tag/v1.5.1, which contains the fix.

**Comment by suvonkar** [comment]
@carhartl ,But still at the end of `$.removeCookie` (https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js#L111) , you are checking the existence of cookie without sub paths, which is not considering the exact path of deleted cookie. This will misguide the developer. It will return always true for the sub path cookie, if it is also not deleted successfully.

**Comment by carhartl** [comment]
Right. As I said, development proceeds in https://github.com/js-cookie/js-cookie and the related code has changed: https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L133 (though I believe not for 1.5, the last version compatible with this plugin).

**Comment by carhartl** [comment]
Btw, when reading a cookie you _can't_ consider a path.

**Comment by carhartl** [comment]
We removed returning a value nevertheless, because it was, as we know now, not reliable.

**Comment by FagnerMartinsBrack** [comment]
@suvonkar 

[Here](https://github.com/js-cookie/js-cookie/blob/v1.5.1/src/js.cookie.js#L137) are the internals from 1.5.1. It still contains the boolean return for backwards compatibility, but we do not encourage relying on it.
