### ISSUE TITLE
A Session Cookie not working

### ISSUE THREAD

**Issue by veeren** [carhartl/jquery-cookie#383]
I am using this code : 
`$.cookie('cookie_name', 'cookie_value', { expires: null, path: '/' });`

**Comment by carhartl** [comment]
Just remove the `expires: null` part...

**Comment by carhartl** [comment]
On the other hand, it should work like that. Which version do you use, and what exactly does not work?

**Comment by veeren** [comment]
I am using shopify and it is "1.8" I guess. 
So my task is to show a popup when a user comes and if user closes the popup it should create a cookie for session only, so it does not show till user session ends. 

What happening here I tried to do by above code and it did not worked, and FYI I am using 
`$.cookie('cookie_name', 'cookie_value', { path: '/' });` 
for other purposes and those cookies remains after session as well with this.

**Comment by FagnerMartinsBrack** [comment]
What does exactly "not work" means? The cookie is not created or when you close and open the window the cookie is still there?

**Comment by veeren** [comment]
Cookie is still there.

**Comment by carhartl** [comment]
Maybe another cookie that's not a session cookie is shadowing the session cookie...

Can you post a screenshot of the contents of the cookie view in the developer console?

**Comment by FagnerMartinsBrack** [comment]
Check [this answer](http://stackoverflow.com/a/10772420) in stackoverflow and make sure "Continue where you left off" setting is disabled in Google Chrome.

**Comment by veeren** [comment]
@FagnerMartinsBrack, Thanks that was the case and fixed it.
