### ISSUE TITLE
Expire Cookie in Hours

### ISSUE THREAD

**Issue by sulthanallaudeen** [carhartl/jquery-cookie#384]
Is it possible to expire the cookie in hours,  

say : set a cookie that expire in 1 hour ?

**Comment by carhartl** [comment]
Yes, you can pass an instance of `Date` for expires or `1/24`.

**Comment by sulthanallaudeen** [comment]
@carhartl  Thanks, 

You mean , if i want to expire cookie at 1 am, then i should do 1/24 like this ?

**Comment by carhartl** [comment]
No. Initially you asked for expiration in 1 hour. Which is what `expires: 1/24` would accomplish, assuming it meant from the time of creation of the cookie on.

If you want the cookie to expire at a particular time in the future, for example at 1 am, you will need to pass an instance of `Date`. That date must represent the desired point of time of expiration. Let's say you want the cookie to expire at the end of this year:

``` javascript
endOfYear = new Date(2016, 11, 31, 24, 59, 59);
$.cookie("foo", "bar", { expires: endOfYear });
```

Information on how to construct and manipulate dates can be found here:
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date
