### ISSUE TITLE
Cookie gets restored magically after some time

### ISSUE THREAD

**Issue by rkyoku** [carhartl/jquery-cookie#387]
I don't understand this one...

The cookie I deleted gets restored (via JS) magically and automatically after some time, even if I refresh the page a couple of times to make sure that code is properly reset.

What I do:
- Click on "logout"
- Remove the cookie
- Reload the page
- Reload the page a couple of times
- I regulary (every 5 seconds) check the cookie (using $.cookie('mycookiename'))
- After a minute or two, the cookie gets magically restored...

Here is an example of debug output:

> app.js:19 check cookie: undefined / 1457031434354
> app.js:19 check cookie: undefined / 1457031439354
> app.js:19 check cookie: undefined / 1457031444354
> app.js:19 check cookie: undefined / 1457031449355
> app.js:19 check cookie: MTk6MTc5NDU2ZDVmOGMxOTk3ZWI= / 1457031454354
> app.js:19 check cookie: MTk6MTc5NDU2ZDVmOGMxOTk3ZWI= / 1457031459355

I do not reset the cookie in my code. The only place where I call $.cookie in order to set the cookie, I got it covered with many debug code and error throwing, so that I could know if it came from here.

It does not.

Any idea? What could I do to help you pinpoint the problem?

I am using the latest Chrome version with developer tools activated, on Windows.

Thank you,

**Comment by FagnerMartinsBrack** [comment]
Can't tell what is going on unless there is some small piece of code I can look into. Have you tried a [newer version](https://github.com/js-cookie/js-cookie/releases) to see if it works?

**Comment by rkyoku** [comment]
I was sure I had the latest version (because this is a new project) but it
happens that I don't (because I have used an old lib file...).
Thanks for pointing the obvious to me, I was confused somehow. I'll try
that and let you know.

Thanks!

Le jeu. 3 mars 2016 à 23:58, Fagner Brack notifications@github.com a
écrit :

**Comment by rkyoku** [comment]
Well, I updated to the latest version, and now I keep getting weird things.
Surely I did something wrong...

Whenever I retrieve my cookie, it contains:
"_authtoken={%22domain%22:%22www.myapp.local%22%2C%22path%22:%22/%22};
path=/_"

No matter what I try: unset it, set it to a new value, open a new private
tab... It always stays, and always at the same weird value. And %22 is a
quote (double quote) character, however I never use double quotes in my
code.

I created 3 handy one-liner functions to set/remove/get a cookie so that I
am sure to pass the exact parameters to each one (domain and path).
Here is the code within:

Cookies.set(name, value, {expires: ttl, domain: COOKIE_DOMAIN, path: '/'});

return Cookies.get(name, {domain: COOKIE_DOMAIN, path: '/'});

Cookies.remove(name, {domain: COOKIE_DOMAIN, path: '/'});

Here is the resulting code in the console:
app.js:294 COOKIE : get authtoken
app.js:368 token:
authtoken={%22domain%22:%22www.myapp.local%22%2C%22path%22:%22/%22};
path=/
app.js:286 COOKIE : remove authtoken
app.js:281 COOKIE : set (name=authtoken value=toto ttl=5
COOKIE_DOMAIN=www.myapp.local)
app.js:294 COOKIE : get authtoken
app.js:289 token:
authtoken={%22domain%22:%22www.myapp.local%22%2C%22path%22:%22/%22};
path=/

I also tried to remove the cookie without specifying the domain and
path. But either way, it doesn't unset it.

Do you have any idea what I did wrong? Why is there double-quotes
inside the (weird) value of the cookie?

I'll continue debugging my code, but I am getting short of ideas right now! :)

Thank you,

**Comment by rkyoku** [comment]
Okay nevermind, I found my mistake.

I read this ticket: https://github.com/js-cookie/js-cookie/issues/145 and I
understood everything.
I was mislead by this line in the docs: "Cookies.get('name'); // =>
undefined (need to read at 'subdomain.site.com')"
I thought it meant that I had to pass the domain as a second parameter to
specify from which domain I wanted to read the cookie from.

I agree one should not pass parameters that are not documented, but I still
think this line in the docs is ambiguous, maybe you could state clearly
that .get() does never take more than 1 argument?

By the way I still have the bug of the reappearing cookie... After 175
seconds or something like that. I have refreshed the page in-between, so
that is not a precise number. But as I said earlier, refreshing the page
does not prevent the cookie from reappearing magically.

Maybe it's not related to the lib, maybe it's a problem in Chrome, or in
one of my plugins.

I'll try a "no-plugins" execution of Chrome to see if it fixes the issue.

app.js:19 check cookie undefined 1457081243783
app.js:19 check cookie undefined 1457081248783
app.js:19 check cookie MTk6MTc5NDU2ZDVmOGMxOTk3ZWI= 1457081253784

**Comment by FagnerMartinsBrack** [comment]
> I agree one should not pass parameters that are not documented, but I still
> think this line in the docs is ambiguous, maybe you could state clearly
> that .get() does never take more than 1 argument?

Pull Request is welcome, you are the only person right now to be able to fix this, because I am biased by being one of the authors of the docs. Please, send a Pull Request changing the docs in a way that you believe will make it clear and remove the ambiguity :)

In the meantime, yeah, try Chrome without any plugins using incognito, maybe it's some extension that is messing up with the page? The missing cookie is really something that never happened, and in order to debug it I need some piece of code, preferentially not a whole page but some snippet in http://jsbin.com or http://jsfiddle.net.

**Comment by FagnerMartinsBrack** [comment]
By the way, shouldn't be better create the issue in the new repo? The README states clearly that:

> New issues should be opened at https://github.com/js-cookie/js-cookie/issues

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
