### ISSUE TITLE
Cookie not set in IE10

### ISSUE THREAD

**Issue by Legends** [carhartl/jquery-cookie#391]
`$.cookie('userlanguage', $("#ddlLanguages option:selected").val(), { domain: "localhost", expires: new Date(2200, 12), path: '/' });`

`$("#ddlLanguages option:selected").val()` returns the correct cookie value.

After that I try to read the cookie: `$.cookie('userlanguage')`
which returns `undefined`.
Works fine in chrome.

**Comment by FagnerMartinsBrack** [comment]
Hi, this repository is not being maintained anymore, please see https://github.com/js-cookie/js-cookie/releases/tag/v1.5.1
