### ISSUE TITLE
Do not create an issue here!

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [carhartl/jquery-cookie#392]
This project was moved to http://github.com/js-cookie/js-cookie.

If you want to upgrade to the new API while maintaining backwards compatibility with `$.cookie`, use the new version [1.5.1](https://github.com/js-cookie/js-cookie/tree/v1.5.1).

Otherwise, if you want to upgrade to the latest version, check the latest release in the [releases page](https://github.com/js-cookie/js-cookie/releases).

If you have support questions, please use [StackOverflow](http://stackoverflow.com/questions/tagged/js-cookie) under the tag [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie).

**Comment by carhartl** [comment]
https://github.com/blog/2460-archiving-repositories 🎉 

@FagnerMartinsBrack I'd like to archive this repository right away, any objections as to why not?

**Comment by FagnerMartinsBrack** [comment]
No objections, as long as the old issues and Pull Requests are still linkable from the js-cookie repo :)

**Comment by carhartl** [comment]
Let‘s try!
