### ISSUE TITLE
Bower crashing if using jquery-cookie 1.4.1

### ISSUE THREAD

**Issue by pixeldrew** [carhartl/jquery-cookie#393]
Guys,

I know this project is deprecated and whilst I want to update my codebase to js-cookies I unfortunately can't. Please don't take away this repo or mess with the tags, it's the only thing backing the bower version. I'm currently getting this error when I try and checkout jquery-cookie#1.4.1

``` sh

bower jquery-cookie#*         validate 1.4.1 against https://github.com/carhartl/jquery-cookie.git#*
bower jquery-cookie#*          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/carhartl/jquery-cookie.git", exit code of #128 fatal: unable to access 'https://github.com/carhartl/jquery-cookie.git/': transfer closed with outstanding read data remaining


```

**Comment by FagnerMartinsBrack** [comment]
It wasn't issue on our side. It seems to have been fixed though, see https://github.com/js-cookie/js-cookie/issues/186#issuecomment-214421045

**Comment by pixeldrew** [comment]
Ah, apologies. lets close this.
