### ISSUE TITLE
Unable to install using Bower

### ISSUE THREAD

**Issue by tatablack** [carhartl/jquery-cookie#394]
Hi, there.
First of all, I know that the project is no longer maintained. :-)

I was wondering whether you changed something in Github's configuration for the project, though; since earlier today, my builds are failing when trying to install `jquery-cookie` via Bower (it's a transitive dependency, so I haven't any control over it).

Specifically, when the following command is issued

`git ls-remote --tags --heads https://github.com/carhartl/jquery-cookie.git`

the output is

`fatal: unable to access 'https://github.com/carhartl/jquery-cookie.git/': transfer closed with outstanding read data remaining`

If I fork the repo and the issue the same command on my fork, it works. So I assume the problem is not with Github itself.

Any ideas? 😕

**Comment by LeoBenoist** [comment]
:+1: The bower should point to https://github.com/js-cookie/js-cookie

**Comment by tatablack** [comment]
Thanks, Leo, I understand that.
However, I'm not using the package directly, it's required by Zurb Foundation 5 in their own `bower.json`, so I can't remove it/update it.

Do you know of a reason why the aforementioned `git` command should fail?

**Comment by LeoBenoist** [comment]
it seems to be github related https://github.com/js-cookie/js-cookie/issues/186

**Comment by FagnerMartinsBrack** [comment]
Seems to have been fixed, see https://github.com/js-cookie/js-cookie/issues/186#issuecomment-214421045

**Comment by tatablack** [comment]
Yep, works now. Sorry for the noise. 👍

**Comment by carhartl** [comment]
Almost certainly a glitch on GitHub. I was seeing the same when trying to clone another repo.
