### ISSUE TITLE
Fail update cookie?

### ISSUE THREAD

**Issue by rogercorrea** [carhartl/jquery-cookie#395]
Please,

I tried use Jquery-cookie to save array in JSON format in the cookie file, but I found error and I don't understand of the why.

In my code the array never updated if the length is major that 10.
I don't understand, but I started use other plugin in the same code and worked now.

My Jquery version is 1.9.1.

`select: function (imagem, selected) {
if ($.listImages == null) {
            $.listImages = Cookies.get('images');
            if ($.listImages == 'null')
                $.listImages = [];
            else
                $.listImages = JSON.parse($.listImages);
        }

```
    if (imagem != null) {

        if (selected)
            $.listImages.push(imagem);
        else
            $.listImages.splice($.inArray(imagem, $.listImages), 1);

        Cookies.set('images', JSON.stringify($.listImages));
    }
```

}`

**Comment by FagnerMartinsBrack** [comment]
Hi, this repository is not being maintained, please take a look [here](https://github.com/carhartl/jquery-cookie/issues/392).

**Comment by FagnerMartinsBrack** [comment]
I have updated the post there to address support questions.
