### ISSUE TITLE
jquery cookie support for http flag true

### ISSUE THREAD

**Issue by affanazul** [carhartl/jquery-cookie#397]
Hey I am using this library and almost in entire application i have use cookies in js, recently i am receaving cookie with http flag true, and this is not recognizing that cookie

But it is getting recognize when http flag is false., I have a other option but for that i need to change many thing in my coding.

Can you help me out in this ?
 var checkcookie = Cookies.get('DesigntoolAuth');

Do i need to add some parameters ?

**Comment by carhartl** [comment]
The http flag means that the cookie is not supposed to be accessible on the client-side, thus this library does not have access to such cookies.

**Comment by FagnerMartinsBrack** [comment]
Please, look at https://github.com/carhartl/jquery-cookie/issues/392.
