### ISSUE TITLE
Cookie Https

### ISSUE THREAD

**Issue by edsonrodsilva** [carhartl/jquery-cookie#399]
I would like to show a popup (modal) only on first access once a day.
The code below not works in a domain with https.
Is there something wrong with my code?

```
setTimeout(function () {
        if ($.cookie('popuphome') === undefined) {
            $('.popuphome').fadeIn();
            $.cookie('popuphome', 'shown', {expires: 1, secure: true});
        }
    }, 5000);
```

**Comment by FagnerMartinsBrack** [comment]
Hi, this repository is not being maintained, please take a look [here](https://github.com/carhartl/jquery-cookie/issues/392).

**Comment by edsonrodsilva** [comment]
Thanks!
