### ISSUE TITLE
suggestion: add function for parse signedcookies in next rev

### ISSUE THREAD

**Issue by sunq0001** [carhartl/jquery-cookie#400]
when i use Express Framework middleware 'express-session' to generate session with secrete key,  it will automatically create encrypted cookie with id "connect.sid". 

from server, there is API `res.signedcookies`, but in client, there is no such API.
May I suggest to add one?

**Comment by carhartl** [comment]
From the express session documentation:

> By default, the HttpOnly attribute is set.

https://github.com/expressjs/session/blob/master/README.md

This means the cookie written by that middleware cannot be read on the client-side, that is jquery-cookie. If you set HttpOnly to false, the cookie should become available.

**Comment by FagnerMartinsBrack** [comment]
@sunq0001
Also, this repository is not being maintained anymore, refer to https://github.com/carhartl/jquery-cookie/issues/392.
For additional context on the "http only" discussion. Please, refer to https://github.com/carhartl/jquery-cookie/issues/122.

**Comment by sunq0001** [comment]
thanks
